# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    currency_api_host: https://openexchangerates.org/api/latest.json?app_id=a4cac5fdafc6456f9bad20550c1c2aef
    rest_endpoints:
        base_server_url: http://server.peymynt.com
        login_endpoint: /api/login_check
        signup_endpoint:  /api/user/sign-up
        reset_password_endpoint:  /api/user/reset-password
        forgot_password_endpoint: /api/user/forget-password
        settings_view_profile_endpoint:  /api/user/profile/get
        settings_update_profile_endpoint:  /api/user/profile/update
        settings_change_password_endpoint: /api/user/password
        settings_get_user_setting_endpoint: /api/user/setting/get
        settings_update_user_setting_endpoint: /api/user/setting/update
        settings_create_user_business_endpoint: /api/business/create
        settings_edit_business_endpoint: /api/business/{business_id}/modify
        settings_view_business_endpoint: /api/business/{business_id}/view
        settings_list_user_business_endpoint: /api/business/list
        settings_make_primary_user_business_endpoint: /api/business/make-primary
        settings_list_emails_connected_accounts_endpoint: /api/email-accounts/load
        settings_create_emails_connected_accounts_endpoint: /api/email-accounts/create
        sales_product_create_endpoint: /api/sales/product/{business_id}/create
        sales_product_update_endpoint:  /api/sales/product/{business_id}/{product_id}/update
        sales_product_view_endpoint: /api/sales/product/{business_id}/{product_id}/view
        sales_product_list_endpoint: /api/sales/product/{business_id}/list
        sales_product_delete_endpoint:  /api/sales/product/{business_id}/{product_id}/delete
        sales_estimate_default_load: /api/sales/estimate/%d/default
        sales_estimate_create: /api/sales/estimate/{business_id}/create
        sales_estimate_list: /api/sales/estimate/{business_id}/list
        sales_estimate_view: /api/sales/estimate/{business_id}/{estimate_id}/view
        sales_estimate_delete: /api/sales/estimate/{business_id}/{estimate_id}/remove
        sales_estimate_update: /api/sales/estimate/{business_id}/{estimate_id}/modify
        customer_add_endpoint: /api/sales/customer/create
        customer_list_endpoint: /api/sales/customer/{business_id}/list
        customer_delete_endpoint: /api/sales/customer/{business_id}/{customer_id}/remove
        customer_view_endpoint: /api/sales/customer/{business_id}/{customer_id}/view
        customer_update_endpoint: /api/sales/customer/{business_id}/{customer_id}/modify
        tax_create_endpoint: /api/tax/create
        tax_list_endpoint: /api/tax/{business_id}/list

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Twig\AppExtension:
            public: false
            tags: ['twig.extension']

    app_rest_bridge:
        class: App\Base\Bridge\RESTBridge
        public: true
        arguments:
            - "@service_container"
            - "@security.token_storage"

    app_system_path:
        class: App\Base\IO\Path
        public: true
        arguments:
            - "@service_container"

    app_content_manager:
        class: App\Base\Manager\ContentManager
        public: true
        arguments:
            - "@service_container"

    app_token_user_provider:
        class: App\Provider\TokenUserProvider

    #service
    app_token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments:
              - "@security.password_encoder"
              - "@service_container"

    app_login_listener:
        class: App\EventListener\LoginListener
        arguments:
            - "@security.authorization_checker"
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@request_stack"
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app_bee_extention:
        class: App\Twig\AppExtension
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: true
        arguments:
            - "@service_container"
            - "@request_stack"
        tags:
            - {name: twig.extention}

    app_authentication_handler:
        class: App\Base\Handler\AuthenticationHandler
        public: true
        arguments:
            - "@router"
            - "@session"

#    estimate_validation:
#        class: App\Validator\EstimateValidation
#
#    estimate_validator:
#        class: App\Validator\Validator
#        public: true
#        arguments:
#            - "@App\Validator\EstimateValidation"